spring:
  datasource:
    url: jdbc:mysql://localhost:9999/capsule?autoReconnect=true
    username: root
    password: pass@word1
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

server:
  port: 8080





